databases:
- name: mattermost
  plan: starter
  region: frankfurt

services:
- type: web
  name: mattermost
  env: docker
  region: frankfurt
  plan: starter
  dockerfilePath: ./app/Dockerfile
  dockerContext: ./app
  disk:
    name: config
    mountPath: /mattermost/config
    sizeGB: 1
  envVars:
  - key: MM_USERNAME
    fromDatabase:
      name: mattermost
      property: user
  - key: MM_PASSWORD
    fromDatabase:
      name: mattermost
      property: password
  - key: MM_DBNAME
    fromDatabase:
      name: mattermost
      property: database
  - key: MM_SQLSETTINGS_DRIVERNAME
    value: postgres
  - key: DB_HOST
    fromDatabase:
      name: mattermost
      property: host
  - key: MM_SERVICESETTINGS_LISTENADDRESS
    value: ":10000"
